export enum HabitColor {
  RED = "RED",
  ORANGE = "ORANGE",
  YELLOW = "YELLOW",
  GREEN = "GREEN",
  BLUE = "BLUE",
  INDIGO = "INDIGO",
  VIOLET = "VIOLET",
  PINK = "PINK",
  ROSE = "ROSE",
  CYAN = "CYAN",
  SKY = "SKY",
  AMBER = "AMBER",
  EMERALD = "EMERALD",
  TEAL = "TEAL",
  LIME = "LIME",
  FUCHSIA = "FUCHSIA",
  PURPLE = "PURPLE",
}
