export enum HabitCategory {
  HEALTH = "HEALTH",
  FITNESS = "FITNESS",
  MENTAL = "MENTAL",
  PRODUCTIVITY = "PRODUCTIVITY",
  RELATIONSHIPS = "RELATIONSHIPS",
  FINANCE = "FINANCE",
  EDUCATION = "EDUCATION",
  CREATIVITY = "CREATIVITY",
  SPIRITUAL = "SPIRITUAL",
  OTHER = "OTHER",
}
